### ISSUE TITLE
New Pastebin Link?

### ISSUE THREAD

**Issue by CyMc888** [SiliconSloth/CryptoNet#1]
Not sure if you are aware, but the Pastebin link expired around a year ago. This isn't too much of a problem due to the fact that you can copy the code off of Github, but I think it would be nice due to how often I install it.

**Comment by SiliconSloth** [comment]
Thanks for letting me know!  Unfortunately "Pastebin’s SMART filters have detected potentially offensive or questionable content in your Paste", so it won't let me make it public anymore.  I don't really know what I can do about that, it's hard to work out what it found offensive in a 5000 line code file.  Apparently other people online have had the same issue, goodbye Pastebin...  

I'll remove the Pastebin link from the repo, I suppose people will just need to download the file from here as you say.  Again, thanks for letting me know, and I'm glad to hear you're making good use of CryptoNet!
