### ISSUE TITLE
Sending a message between clients

### ISSUE THREAD

**Issue by olliejohnson** [SiliconSloth/CryptoNet#3]
Is there a way to send a message from one client to the server to have it redirected to another client specified by the client sending the message

**Comment by SiliconSloth** [comment]
Hi @olliejohnson , the challenge there is that you need a way for the clients to identify each other, which is not built into CryptoNet.  I would recommend assigning a username to each client, then on the server you could have a table mapping usernames to sockets used to communicate with the clients.  The sending client would need to specify the username to send the message to, then the server can forward the message via the socket in the username table.  I hope that helps!
