### ISSUE TITLE
Cannot load global API because of `shell` index error

### ISSUE THREAD

**Issue by DevKoenv** [SiliconSloth/CryptoNet#5]
I downloaded the raw file using `wget`, the testServer.lua has the example code from the readme but I keep getting an error that i can't load the cryptoNet API
![image](https://github.com/SiliconSloth/CryptoNet/assets/42892277/caada6a7-a4fd-45b5-b032-3f8b93f08242)

I'm not sure if this is a problem at my end, or if this is a problem with CryptoNet but I can't seem to fix it

**Comment by SiliconSloth** [comment]
I've just tried this on my end and it works fine.  What version of ComputerCraft are you using?  That line of code shouldn't actually be running there, I suspect the check on line 5215 is returning true even though you are running via API.  As a quick fix you could try hardcoding it to false.

**Comment by DevKoenv** [comment]
i'm using the latest version of cryptonet and craftos 1.8 on 1.16.5
for some reason it works now without doing anything different... anyway i'll keep that fix in mind for if it happends again, thanks for the help!
