### ISSUE TITLE
Require Issue On Line 5215

### ISSUE THREAD

**Issue by CyMc888** [SiliconSloth/CryptoNet#6]
Seems like some code for debugging has an issue on line 5215, the program crashes on startup.
![image](https://github.com/user-attachments/assets/1fc56f37-3a7d-4c8f-b1ff-df385fc96921)

**Comment by CyMc888** [comment]
I just checked the code and it seems to be an issue with command line interface.  Not sure if this is due to me using the latest version of computer craft or not. For now I'm just going to force the if statement to false.

**Comment by SiliconSloth** [comment]
Hi there, please could you try replacing that check with `shell ~= nil and debug.getinfo(2).name ~= "require"`? Hopefully that will be less version specific.

**Comment by CyMc888** [comment]
I just checked and that did seem to work. Thank you!
