### ISSUE TITLE
Attempt to index a nil value on line 5215

### ISSUE THREAD

**Issue by zimavi** [SiliconSloth/CryptoNet#7]
In attempt to run `cryptoNet initCertAuth` program crashes indicating a nil value on line 5215 (`if shell ~= nil and debug.getinfo(2).name ~= "require"`)

![screenshot](https://github.com/user-attachments/assets/8d113789-1422-4c2b-bd8f-cd2b4c658213)

EDIT: Running Minecraft 1.20.1 (Fabric) with latest version of CC:Tweaked installed (from Modrinth)

**Comment by SiliconSloth** [comment]
Hi there, can you try changing that line to `if shell ~= nil and (debug.getinfo(2) == nil or debug.getinfo(2).name ~= "require") then`?

**Comment by der-fruhling** [comment]
> Hi there, can you try changing that line to `if shell ~= nil and (debug.getinfo(2) == nil or debug.getinfo(2).name ~= "require") then`?

This change seems to fix this issue.
